#!/usr/bin/python3
import re
import subprocess

subprocess.check_call([ "make", "html" ])
rst_sources = [
	"introduction",
	"usage",
	"problems",
	"testing",
]

readme = [ ]
for source in rst_sources:
	source = "source/" + source + ".rst"
	with open(source) as f:
		readme.append(f.read())
readme = "\n".join(readme)

h12_regex = re.compile("^(?P<title>.*)\n(?P<htype>[*=-]+)$", flags = re.MULTILINE)
def replace_h12(match):
	args = match.groupdict()
	if args["htype"][0] == "*":
		return "# %s" % (args["title"])
	else:
		return "## %s" % (args["title"])
readme = h12_regex.sub(replace_h12, readme)


code_regex = re.compile("(\n    [^\n]*)+", flags = re.MULTILINE)
def replace_code(match):
	text = match.group(0)
	lines = text.split("\n")[1:]
	lines = [ line[4:] for line in lines ]
	return "\n```\n" + "\n".join(lines) + "\n```\n"
readme = code_regex.sub(replace_code, readme)

readme = re.sub(r"::\s*\n", ":\n", readme)
readme = re.sub(r"\n\.\. warning:\n", "\n*WARNING*\n", readme)
readme = re.sub(r"\n\.\. .+:\n", "", readme)

with open("../README.md", "w") as f:
	f.write(readme)
